name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - '"dev"'

env:
  PROJECT_ID: 'ecom-chat-437005'
  GAR_NAME: 'verta-chat'
  GAR_LOCATION: 'us-east1' 
  SERVICE: 'verta-service'
  REGION: 'us-east1' 
  
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker "$${{ env.GAR_LOCATION }}-docker.pkg.dev"
  
      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="$${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" -f Dockerfile .
          docker push "${DOCKER_TAG}"
          
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}'
          env_vars: |
            LANGCHAIN_API_KEY= ${{ env.LANGCHAIN_API_KEY }}
            OPENAI_API_KEY= ${{ env.OPENAI_API_KEY }}
            LANGCHAIN_PROJECT = "eCommerce Chatbot"
            HF_TOKEN = ${{ env.HF_TOKEN }}
            GROQ_API_KEY = ${{ env.GROQ_API_KEY }}
            LANGFUSE_SECRET_KEY= ${{ env.LANGFUSE_SECRET_KEY }}
            LANGFUSE_PUBLIC_KEY= ${{ env.LANGFUSE_PUBLIC_KEY }}
            LANGFUSE_HOST= https://us.cloud.langfuse.com
            DB_USER="postgres"
            DB_PASS="postgres"
            DB_NAME="postgres"
            INSTANCE_CONNECTION_NAME="ecom-chat-437005:us-east4:postgres"
            GCS_BUCKET_NAME="ecom-chat"
      
      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
